UCLALibrary/dlcs-staff-ui

dlcs_staff_ui/urls.py, oral_history/forms.py, oral_history/templates/oral_history/base.html, oral_history/templates/oral_history/project.html, oral_history/urls.py, oral_history/views.py
Added scaffolding for blank Projects form. This does not save yet, and may be tested by navigating to:
`/projects/new`
A blank form with all fields in the Projects model should be displayed, except the field for primary key
=> Sys 751/project form

Dockerfile, requirements.txt
This PR adds 3 programs for processing derivatives, all from Debian 11 (Bullsye) repos:
* ffmpeg 4.3.3-0
* imagemagick 6.9.11-60 Q16
* jhove 1.20.0
For imagemagick, note that there is no **_magick_** command via the official package, but the individual commands like **_convert_** and **_conjure_** are available.
This also adds openjdk 11.0.14 - java is needed by jhove.
Finally, it adds python wrappers for ffmpeg and imagemagick (nothing relevant found for jhove):
* [ffmpeg-python](https://github.com/kkroening/ffmpeg-python)
* [wand](https://docs.wand-py.org/en/0.6.7/) for imagemagick
If different versions or wrappers are needed, please let me know.
=> SYS-784: Install derivative processing programs and python wrappers

README.md, oral_history/admin.py, oral_history/templates/oral_history/table.html, oral_history/urls.py, oral_history/views.py
Connected to [SYS-780](https://jira.library.ucla.edu/browse/SYS-780)
A _Harness_ page was added with a link to the forthcoming page of SYS-781.
---
This is a temporary page used to call the Oral History media processing script. It passes the selected item's ARK to another Django page from which the associated media file may be selected and sent to the OH script.
**Typical Screenshots**
-----
**Changed Files**
```
oral_history/
templates/oral_history/
table.html
admin.py
urls.py
views.py
README.md
```
=> SYS-780 - Create Django page which provides test data for file upload

.docker-compose_django.env, README.md, dlcs_staff_ui/settings.py, logs/.gitignore
This PR adds configuration for basic logging.  Documentation is included in [this branch's README.md](https://github.com/UCLALibrary/dlcs-staff-ui/compare/SYS-803/enable_logging?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
A future enhancement may include display of logs within the UI, via https://pypi.org/project/django-log-viewer/ - but for now, logging to file is sufficient.
=> SYS-803: Enable basic logging

oral_history/management/commands/run_script.py, oral_history/scripts/process.py
Connected to [SYS-785](https://jira.library.ucla.edu/browse/SYS-785)
Messages related to success/failure of the media file processing script need to be made available in the Django environment. In a follow-on ticket, [SYS-805](https://jira.library.ucla.edu/browse/SYS-805), the message will be displayed in the same window that initiated the file upload request using the Django messaging framework. File information about the uploaded file is sent from the media processing script.
-----
**Acceptance criteria:**
-----
**Typical Screenshots**
-----
**Changed Files**
```
oral_history/
management/
commands/
run_script.py
scripts/
process.py
```
=> SYS-785 - Display information once processing has finished

.github/workflows/build_docker_hub.yml
This PR adds a GitHub Action script to build/push the Django image to Docker Hub.
It's intended to run only on merge to the `main` branch, and the GH repo has been configured to require approved pull requests before such a merge can happen.
=> SYS-807: Add github action script to build/push to Docker Hub

dlcs_staff_ui/settings.py, oral_history/management/commands/run_script.py, oral_history/scripts/process.py, oral_history/templates/oral_history/base.html, oral_history/templates/oral_history/fileupload.html, oral_history/views.py
Connected to [SYS-805](https://jira.library.ucla.edu/browse/SYS-805)
The Django Messaging Framework was implemented to display status or error messages in the current page being viewed. Status or error messages from the media file processing script display in the same window used by the file upload process (display on the file-picker page).
-----
**Acceptance criteria:**
-----
**Typical Screenshots**
-----
**Changed Files**
```
dlcs_staff_ui/
settings.py
oral_history/management/commands/
run_script.py
scripts/
process.py
templates/oral_history/
base.html
fileupload.html
views.py
```
=> SYS-805 - Implement the django messaging framework to display status or error messages

oral_history/admin.py, oral_history/management/commands/process_file.py, oral_history/views.py
Connected to [SYS-808](https://jira.library.ucla.edu/browse/SYS-808)
NOTE: admin.py is unchanged. It is included because spacing was automatically changed by VSCode.
After a file is processed, the submitted file is copied to a destination location (the masters directory), and the derivative file (submaster) is copied to a different location. Create a function that, when supplied with mime_type and item_ark, returns the location for the derivative.
These destination locations are located in the PROJECTS table.
-----
**Acceptance criteria:**
-----
**Typical Screenshots**
-----
**Changed Files**
```
oral_history/
admin.py
management/
commands/
process_file.py
```
=> SYS-808 - Get target directory for derivative

docker_scripts/entrypoint.sh, oral_history/forms.py
This PR redoes the work from #32 , which had to be temporarily removed due to a problem found when testing #33 .
The changes to `forms.py` are the same as before.  The fix is via `entrypoint.sh`: adding a flag to `migrate` which tells that to skip system checks when it runs.  Otherwise, Django does a check, sees that a model (`FileGroups`) is being referenced in `forms.py`... but that model does not yet exist when migrations are run against an empty database, so the migrations immediately fail.
This is a somewhat niche case, but does come up during local development when a local db refresh is needed / wanted.
=> SYS-846: Get FILE_GROUPS data from database

.docker-compose_django.env, charts/templates/configmap.yaml, charts/values.yaml, media_dev/.gitignore, media_dev/oh_lz/.gitignore, media_dev/oh_source/.gitignore, media_dev/oh_wowza/.gitignore
This PR adds 3 environment variables, which should be used by file-processing scripts:
* `DJANGO_OH_LIBPARTNERS` # Oral History source files
* `DJANGO_OH_MASTERSLZ` # Masters "shadow landing zone"
* `DJANGO_OH_WOWZA` # Wowza
It also creates "mock" directories within the Django file system, anchored at `media_dev/`, for scripts to use in development.  Files added to these directories will not be added to the repository, and will need to be deleted manually during development.  If extra directories are needed (say for organizing masters) they can be added to the relevant `.gitignore` exclusions as they're identified.
`DJANGO_OH_LIBPARTNERS` probably could replace `DJANGO_DLCS_FILE_SOURCE`, but I've kept them separate for now.
This also adds these 3 environment variables to the embedded Helm …
=> SYS-854: Add environment variables for media directories

oral_history/management/commands/process_file.py
Functions have been added to calculate the appropriate file name given an item ark, file use (master, submaster...) and extension (mp3, wav).
To test, in python console run the following given the existing test data in the python interpreter on the django container:
```
from django.db.models import Max
from oral_history.models import ContentFiles
exec(open("oral_history/management/commands/process_file.py").read())
get_new_content_file_name("21198/zz002dx6rf", "submaster", "mp3")
'21198-zz002dx6rf-1-submaster.mp3'
cf = ContentFiles.objects.get(fileid_pk=1)
cf.file_sequence = "1"
cf.save()
get_new_content_file_name("21198/zz002dx6rf", "submaster", "mp3")
'21198-zz002dx6rf-2-submaster.mp3'
```
This calculates the appropriate file name given the existing sequence in the `ContentFiles` table, …
=> Sys 857/calculate file name

.docker-compose_django.env, .gitignore, dlcs_staff_ui/settings.py, docker_scripts/entrypoint.sh, requirements.txt
This PR updates the application to be deployment-ready (I hope...):
* Installs and configures `gunicorn` for application server
* Installs and configures `whitenoise` for static file handling
* Adds 3 environment variables expected but not configured
Tested locally by setting `DJANGO_RUN_ENV=test`.  The output shows a warning that a `static` directory is expected in configuration but not present, which is OK for now.
=> SYS-853: Update modules/settings/environment for deployment

oral_history/templates/oral_history/logs.html, oral_history/urls.py, oral_history/views.py
This PR adds a __very__ quick & dirty ability to view the current log file `logs/application.log` at `/view_logs`.  This is solely to allow devs to view logs for the deployed application, which they can't do now.
This should be protected by Django login, but I had trouble getting that to work.  Having the log publicly available could be a security risk, mitigated by us not logging any secrets or sensitive information.
Testing:
* Confirm `logs/application.log` exists - restarting the Django container will do that, if needed.
* Visit http://127.0.0.1:8000/view_logs
=> SYS-861: Show application log via web

oral_history/forms.py, oral_history/settings.py, oral_history/views.py
This PR 
* Limits the file group list on `uploadfile` form to just the values for the Oral History project
* Limits the project items on `table` test harness view to the "first" 10 values for Oral History
* Replaces hard-coded OH project_id with value from OH application-specific settings file
Tested with both local database (no changes since sample data is already limited) and when connected to the DLCS QA database, both via `manage.py shell` (easy) and the UI itself (harder, not recommended...).
=> SYS-872: Limit form and view to project 80, Oral History

.docker-compose_django.env, charts/templates/configmap.yaml, charts/test-dlcsstaffui-values.yaml, charts/values.yaml, oral_history/management/commands/process_file.py
This PR fixes a bug in `get_local_root_dir()`, which could return `None`, leading to problems in the calling `calculate_destination_dir()`: including `None` in a python f-string results in the string `None`, not an exception as expected with regular string concatenation.
Since returning `None` from `get_local_root_dir()` indicates a problem, I changed that routine to throw `ValueError` instead.  The caller catches that and the error passes up to the UI.
The bug occurred in several cases, because two environment variables were not yet defined.  Both of those have been changed to use `DJANGO_OH_STATIC`, which now is defined.  Most of the updates in this PR are for the Helm chart, though only as placeholders for now since the underlying mount has not yet been added.
Testing of the …
=> SYS-879: Fix bug with None in get_local_root_dir()

charts/test-dlcsstaffui-values.yaml
This PR changes `dlcs_file_source` to point to a specific upload directory in the deployed container.  This should avoid the problem caused by too many files in the main directory.
=> SYS-874: Change dlcs_file_source to specific upload directory

oral_history/management/commands/process_file.py, oral_history/scripts/image_processor.py
Addresses a few issues:
* Adds argument to submit admin group title for similar parameters (submaster and thumbnail use same admin terms)
* Adds submaster generation to `process_tiff()`
* Helper methods in `ImageProcessor()` for thumbnail and submaster options
To test, in django shell run:
`python manage.py process_file -a 21198/zz002dx6v0 -f /home/django/dlcs-staff-ui/samples/example_project/sample.tiff -g 562`
Expected behavior:
3 new files are created, the sequence number may be different but they should all be the same (in case below, 10)
`media_dev/oh_static/oralhistory/nails/21198-zz002dx6v0-10-thumbnail.jpg`
`media_dev/oh_static/oralhistory/submaster/21198-zz002dx6v0-10-submaster.jpg`
`media_dev/oh_lz/oralhistory/masters/21198-zz002dx6v0-10-master.tiff`
=> Sys 877/image submaster add

.github/workflows/build_docker_hub.yml, charts/test-dlcsstaffui-values.yaml
This PR updates the `build_docker_hub` GitHub Action:
* Reads image tag from Helm chart values file
* Uses that value to tag the image built and pushed to Docker Hub
Developer is responsible for updating chart with new image tag.
=> SYS-880: Initial tagged deployment

charts/test-dlcsstaffui-values.yaml, oral_history/forms.py
This PR fixes a ~bug~ unexpected behavior where Django caches form options at startup.  In this case, the `FilePathField` used to select a file for upload does not see changes to the file system, so new / deleted files are not reflected in the `file_name` selector unless Django is restarted.
Manual testing:
```
$ ls -al > samples/fake_interviews/foobar1.txt
```
=> SYS-881: Work around form caching hiding file system changes

charts/test-dlcsstaffui-values.yaml, oral_history/forms.py, oral_history/views.py
This PR fixes a bug introduced by SYS-881 (#62), which caused a TypeError when the form is submitted:
```
Exception Value: __init__() takes 1 positional argument but 2 were given
File "/home/django/dlcs-staff-ui/oral_history/views.py", line 20, in upload_file
form = FileUploadForm(request.POST)
```
Either the code I copy/pasted was incomplete, or Django has changed since that was posted.  In our situation at least, the overridden `__init__` methods needed both `*args` and `**kwargs` passed to them, not just `**kwargs` as I did.
Tag bumped to `v0.7.1` for deployment.
=> SYS-884: Fix TypeError bug with form's overridden init()

charts/test-dlcsstaffui-values.yaml, oral_history/templates/oral_history/base.html, oral_history/templates/oral_history/fileupload.html, static/js/main.js
This PR adds a simple javascript function.  When the upload form is submitted:
* Change the "Upload" button to say "Please wait..."
* Disable the "Upload" button until the requested processing is done.
Bumps image tag to `v0.8.2` for deployment.
This is awkward to test locally as our sample files are so small there's nothing to wait for.  I tested by inserting `import time; time.sleep(10)` into `process_file` just above the call to `process_media_file`.  See screenshots for sample results:
=> SYS-893: Show 'Please Wait' message after submitting file upload form

charts/test-dlcsstaffui-values.yaml, oral_history/management/commands/process_file.py, oral_history/scripts/audio_processor.py, oral_history/scripts/file_processor.py, oral_history/scripts/image_processor.py
A few corrections for values set in a ContentFile object
- location_type always set to `URL`, previously the values were either URL or database. Only URL is valid now
- file_use is set to either Master, Submaster or Thumbnail (first letter is capitalized to match legacy data)
- file_name is set to the destination file name, without path
- content_type is set to the media type, with Audio and Image capitalized to match legacy data
Other items of note:
- `overwrite_output=True` added to ffmpeg call to overwrite existing output
- file_sequence bug found when more than 9 files are added, a separate ticket and possible solution added
To verify:
Start bash shell on container and run the following:
`python manage.py process_file -a 21198/zz002dx6v0 -f …
=> Corrected ContentFiles fields in processor files

charts/test-dlcsstaffui-values.yaml, oral_history/scripts/audio_processor.py, oral_history/scripts/file_processor.py, oral_history/scripts/image_processor.py
This PR adds a `get_url()` function which returns the URL needed for `file_path`, for non-masters only.
The function currently is in all 3 Processor scripts, with minor differences which should be reconciled later with refactoring of the Processor scripts; marked with `TODO` for the future.
Bumps image tag version to `v0.8.4`
**Updated data from local testing**
```
file_path = 'media_dev/oh_static/oralhistory/text/submasters/21198-zz002dx6rf-10-submaster.txt', url = 'https://static.library.ucla.edu/oralhistory/text/submasters/21198-zz002dx6rf-10-submaster.txt'
file_path = 'media_dev/oh_static/oralhistory/pdf/submasters/21198-zz002dx6rf-10-submaster.pdf', url = 'https://static.library.ucla.edu/oralhistory/pdf/submasters/21198-zz002dx6rf-10-submaster.pdf'
file_path = …
```
=> SYS-895: Set file_location correctly for non-masters

charts/test-dlcsstaffui-values.yaml, oral_history/management/commands/process_file.py, oral_history/templates/oral_history/fileupload.html, oral_history/views.py
This PR enables the display of URLs (or paths, currently, for masters) for processed files.  A new message appears on the upload form after successful processing, listing the URLs/paths along with their `file_use` values (Master, Submaster, Thumbnail).
URLs don't display directly, but are hyperlinked via the `file_use` value.  Paths display in full.
The changes consist of:
* New function `get_url_message()` which builds the HTML from `content_file_data`
* New parameter to `process_file` so the view can pass the request needed by Django's messaging framework
* Addition of the `request` parameter where needed to pass it to other functions
* Bump image tag version to `v0.8.5`
Django's `messages` is effectively global, so does not need to be passed from the view to `process_file` to …
=> SYS-892: Display file URLs (or paths) after processing

charts/test-dlcsstaffui-values.yaml, oral_history/management/commands/process_file.py
This PR fixes a bug calculating the `max` of `file_sequence`.  This data is numeric, but stored in the database (and model) as an un-normalized string, so does not automatically sort as a number.
This modified `get_next_seq_from_content_files()` to annotate with an `int_sequence` field which is an integer via Oracle's `to_number()` .  The query then aggregates on `max(int_sequence)` and returns that correctly-calculated value.
Also bumps image tag version to `v0.8.6`
Testing: Repeatedly process the same file in the UI and observe the `Master` filename as the sequence increments 9 -> 10 -> 11 etc.
Screenshot from http://127.0.0.1:8000/admin/oral_history/contentfiles/
=> SYS-894: Handle file_sequence as integer

charts/test-dlcsstaffui-values.yaml, oral_history/templates/oral_history/base.html, oral_history/templates/oral_history/fileupload.html, static/css/style.css
This PR makes minor improvements to the visual appearance of `/table` and `/upload_file`:
* Page bodies are now top- and left-padded, instead of flush against those sides of the browser window
* Project item info on `/upload_file` is now in a box, with more padding & margin for visual distinction from the rest of the page
* Form elements on `/upload_file` are now in a table instead of using Django's `form.as_p`, reducing the space between elements.
Testing: Look at stuff.
=> SYS-897: Improve template styling

charts/test-dlcsstaffui-values.yaml, oral_history/management/commands/process_file.py, oral_history/scripts/audio_processor.py, oral_history/scripts/file_processor.py, oral_history/scripts/image_processor.py
This PR fixes two problems with static paths and URLs:
* Update processor `get_url()` functions to distinguish between relative and absolute paths
* Update `process_file.get_app_folder_name()` to use nested folder instead of parallel folder for `test` environment
Bumps image tag to `v0.9.0`
Tested in a bash shell on the container (necessary for python to have the right environment).  In `dev` and `prod` environments the app folder is `/oralhistory`;  in `test` environment, `/oralhistory/oralhistory-test`.
```
django@b8f662118b75:~/dlcs-staff-ui$ export DJANGO_RUN_ENV=dev
django@b8f662118b75:~/dlcs-staff-ui$ python manage.py shell
>>> import oral_history.management.commands.process_file as pf; pf.get_app_folder_name()
'/oralhistory'
django@b8f662118b75:~/dlcs-staff-ui$ export …
```
=> SYS-898: Fix static path/url problems

.docker-compose_django.env, charts/Chart.yaml, charts/templates/configmap.yaml, charts/test-dlcsstaffui-values.yaml, charts/values.yaml, oral_history/management/commands/process_file.py
This PR adds a `use_test_dirs` variable, to separate that functionality from the environment the application is running in.
It also points the application to the production database.
Chart version and image tag versions have been updated.
@sgurnick Please review the chart changes to be sure I didn't miss anything.
@kjallen Please review the code changes (trivial, but still...).  I tested locally by updating `DJANGO_USE_TEST_DIRS` in `.docker_compose_django.env` and restarting the application.
=> SYS-912: Add 'use_test_dirs' variable, and point application to production

charts/test-dlcsstaffui-values.yaml, oral_history/management/commands/process_file.py, oral_history/scripts/file_processor.py, oral_history/scripts/image_processor.py
Some tweaks to how the folders are created --
Assumptions : All mount points end with an oralhistory folder (or in the case of masters, designated oralhistory)
If `DJANGO_USE_TEST_DIRS` is *not* set, ignore the app_folder name altogether. This is the case for production.
If `DJANGO_USE_TEST_DIRS` *is* set, use only the `webappname + test` as the folder, rather than `webappname/webappname+test`
Update file and image script `get_url` method url stub to include `/oralhistory`
=> Sys 925/static path fix
